### ISSUE TITLE
Add footer about Famo.us organizing

### ISSUE THREAD

**Issue by ajpiano** [jQuerySF/2015.jquerysf.com#3]
Typically 3rd party events have some kind of footer about who's organising - for instance the footer of [jqueryuk.com](http://jqueryuk.com). I think it would be good to add this to be clear about who's putting the conf together!

**Comment by MylesBorins** [comment]
I think that the organizers section makes it clear who is organizing now.  Thoughts?

**Comment by MylesBorins** [comment]
Closing
